-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 16:08:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `registro` ;

-- -----------------------------------------------------
-- Schema registro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registro` DEFAULT CHARACTER SET utf8 ;
USE `registro` ;

-- -----------------------------------------------------
-- Table `registro`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `registro`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `nControl` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `carrera` INT NULL,
  `semestre` INT NULL,
  `sexo` INT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro`.`Ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro`.`Ubicacion` ;

CREATE TABLE IF NOT EXISTS `registro`.`Ubicacion` (
  `idUbicacion` INT NOT NULL AUTO_INCREMENT,
  `nombreUbicacion` VARCHAR(45) NOT NULL,
  `pisos` INT NULL,
  `descripcion` CHAR(80) NULL,
  PRIMARY KEY (`idUbicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro`.`Salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro`.`Salon` ;

CREATE TABLE IF NOT EXISTS `registro`.`Salon` (
  `idSalon` INT NOT NULL AUTO_INCREMENT,
  `identificador` VARCHAR(45) NOT NULL,
  `piso` INT NULL,
  `categoria` INT NULL,
  `capacidadUso` INT NULL,
  `climas` BINARY NULL,
  `horaApertura` TIME NULL,
  `horaCierre` TIME NULL,
  `Ubicacion_idUbicacion` INT NOT NULL,
  PRIMARY KEY (`idSalon`),
  INDEX `fk_Salon_Ubicacion1_idx` (`Ubicacion_idUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Salon_Ubicacion1`
    FOREIGN KEY (`Ubicacion_idUbicacion`)
    REFERENCES `registro`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro`.`Uso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro`.`Uso` ;

CREATE TABLE IF NOT EXISTS `registro`.`Uso` (
  `idUso` INT NOT NULL AUTO_INCREMENT,
  `Alumno_idAlumno` INT NOT NULL,
  `Salon_idSalon` INT NOT NULL,
  `dia` DATE NULL,
  `horaEntrada` TIME NULL,
  PRIMARY KEY (`idUso`),
  INDEX `fk_Uso_Alumno_idx` (`Alumno_idAlumno` ASC) VISIBLE,
  INDEX `fk_Uso_Salon1_idx` (`Salon_idSalon` ASC) VISIBLE,
  CONSTRAINT `fk_Uso_Alumno`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `registro`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Uso_Salon1`
    FOREIGN KEY (`Salon_idSalon`)
    REFERENCES `registro`.`Salon` (`idSalon`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
